// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvg-vsDo-8sFzo6jVbeUWrRPEyFreO32I',
    appId: '1:418457726672:web:4d0d18604a93fbdd93f8d5',
    messagingSenderId: '418457726672',
    projectId: 'creditform-d505d',
    authDomain: 'creditform-d505d.firebaseapp.com',
    storageBucket: 'creditform-d505d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALeedNoxxo1sTVo_j53MmUcXtofQwls48',
    appId: '1:418457726672:android:dd1887ce83f3290293f8d5',
    messagingSenderId: '418457726672',
    projectId: 'creditform-d505d',
    storageBucket: 'creditform-d505d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgCnuQkrW6YE4VSaoqhzngn_5iJ8LUO2A',
    appId: '1:418457726672:ios:c2cea7e50d772ecb93f8d5',
    messagingSenderId: '418457726672',
    projectId: 'creditform-d505d',
    storageBucket: 'creditform-d505d.appspot.com',
    iosBundleId: 'com.example.backofficeAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgCnuQkrW6YE4VSaoqhzngn_5iJ8LUO2A',
    appId: '1:418457726672:ios:c2cea7e50d772ecb93f8d5',
    messagingSenderId: '418457726672',
    projectId: 'creditform-d505d',
    storageBucket: 'creditform-d505d.appspot.com',
    iosBundleId: 'com.example.backofficeAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsjtmEM78L8qPEPolG5kIFyTCv0RVbXSo',
    appId: '1:418457726672:web:54193824c38c626a93f8d5',
    messagingSenderId: '418457726672',
    projectId: 'creditform-d505d',
    authDomain: 'creditform-d505d.firebaseapp.com',
    storageBucket: 'creditform-d505d.appspot.com',
  );
}
